services:
  yalpdb:
    image: postgres:latest
    container_name: yalpdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: yalp
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - yalp  

  yalp-redis:
    image: redis:latest
    container_name: yalp-redis
    ports:
      - "6378:6379"
    networks:
      - yalp  

networks:
  yalp: 
    driver: bridge 
  openbudget: 
    external: true

volumes:
  postgres_data:
