services:
  udevslabs-yalp:
    image: postgres:latest
    container_name: udevslabs-yalp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: yalp
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - udevslabs-yalp

  udevslabs-yalp-redis:
    image: redis:latest
    container_name: udevslabs-yalp-redis
    ports:
      - "6378:6379"
    networks:
      - udevslabs-yalp
      
networks:
  udevslabs-yalp: 
    external: true

volumes:
  postgres_data: