services:
  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    volumes:
      - minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    cpu_period: 100000
    cpu_quota: 20000
    mem_limit: 1G
    mem_reservation: 512M
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
      MINIO_ADDRESS: ":9000"
      MINIO_CONSOLE_ADDRESS: ":9001"
    command: minio server /data
    networks:
      - udevslabs-yalp

  app1:
    build: .
    container_name: udevs-yalp-1
    env_file:
      - .env  
    ports:
      - "8081:8080"
    networks:
      - udevslabs-yalp
    depends_on:
      - minio
    cpuset: "0"
    cpu_period: 100000
    cpu_quota: 20000 
    mem_limit: 1G
    mem_reservation: 512M
    restart: unless-stopped

networks:
  udevslabs-yalp:
    external: true
    driver: bridge 

volumes:
  minio:
