services:
  app:
    build: .
    container_name: udevs-yalp
    env_file:
      - .env                # Atrof-muhit o'zgaruvchilarni yuklash
    ports:
      - 8080:8080           # App konteynerining tashqi va ichki portlari
    networks:
      - udevslabs-yalp
         


networks:
  udevslabs-yalp:
    external: true  