services:
  app:
    build: .
    container_name: udevs-yalp
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - udevslabs-yalp


networks:
  udevslabs-yalp: 
    external: true